services:
  mysql:
    image: mysql:8.0
    container_name: logistics-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: logistics_db
    
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    build: .
    container_name: logistics-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_NAME: logistics_db
      PORT: 3000
    depends_on:
      - mysql

volumes:
  mysql_data: